server:
  port: 8888

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///seckill?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: admin
  redis:
    port: 6379
    database: 2
    password: redispassword
    host: 47.105.184.154

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    #开启驼峰式命名映射
